job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  kind: CronJob
  schedule: "*/20 * * * *"
  startingDeadlineSeconds: 180
  concurrencyPolicy: Forbid
  environment:
    IDAM_REDIRECT_URL: https://fpl-case-service-*.service.core-compute-aat.internal/oauth2/callback

global:
  jobKind: CronJob
